### ISSUE TITLE
Activating extension `Zignd.html-css-class-completion` failed: Cannot find module 'bluebird'.

### ISSUE THREAD

**Issue by alanaasmaa** [zignd/HTML-CSS-Class-Completion#106]
DOes not work after last update

```
Here is the error stack:  Error: Cannot find module 'bluebird'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.J.X.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:709)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\AlanAasmaa\.vscode\extensions\Zignd.html-css-class-completion-1.14.0\out\src\extension.js:11:18)
	at Object.<anonymous> (C:\Users\AlanAasmaa\.vscode\extensions\Zignd.html-css-class-completion-1.14.0\out\src\extension.js:146:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.J.X.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:709)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Function.a [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:31:863)
```

**Comment by zignd** [comment]
There was another issue reporting this same problem at the time, it is already fixed by now. Thanks for the report.
