### ISSUE TITLE
Unable to Install On Visual Studio 2017

### ISSUE THREAD

**Issue by ashishpatel1992** [zignd/HTML-CSS-Class-Completion#126]
Unable to install it
```
Error Log:
13-Apr-18 1:09:30 PM - Microsoft VSIX Installer
13-Apr-18 1:09:30 PM - -------------------------------------------
13-Apr-18 1:09:30 PM - vsixinstaller.exe version:
13-Apr-18 1:09:30 PM - 15.6.152+ge95e4dd1ce
13-Apr-18 1:09:30 PM - -------------------------------------------
13-Apr-18 1:09:30 PM - Command line parameters:
13-Apr-18 1:09:30 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\hp\Downloads\Zignd.html-css-class-completion-1.17.1.vsix
13-Apr-18 1:09:30 PM - -------------------------------------------
13-Apr-18 1:09:30 PM - Microsoft VSIX Installer
13-Apr-18 1:09:30 PM - -------------------------------------------
13-Apr-18 1:09:30 PM - Initializing Install...
13-Apr-18 1:09:31 PM - Extension Details...
13-Apr-18 1:09:31 PM - 	Identifier         : html-css-class-completion
13-Apr-18 1:09:31 PM - 	Name               : IntelliSense for CSS class names in HTML
13-Apr-18 1:09:31 PM - 	Author             : Zignd
13-Apr-18 1:09:31 PM - 	Version            : 1.17.1
13-Apr-18 1:09:31 PM - 	Description        : CSS class name completion for the HTML class attribute based on the definitions found in your workspace.
13-Apr-18 1:09:31 PM - 	Locale             : en-US
13-Apr-18 1:09:31 PM - 	MoreInfoURL        : 
13-Apr-18 1:09:31 PM - 	InstalledByMSI     : False
13-Apr-18 1:09:31 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
13-Apr-18 1:09:31 PM - 
13-Apr-18 1:09:31 PM - 	SignatureState     : Unsigned
13-Apr-18 1:09:31 PM - 	Supported Products : 
13-Apr-18 1:09:31 PM - 		Microsoft.VisualStudio.Code
13-Apr-18 1:09:31 PM - 			Version : 
13-Apr-18 1:09:31 PM - 
13-Apr-18 1:09:31 PM - 	References         : 
13-Apr-18 1:09:31 PM - Signature Details...
13-Apr-18 1:09:31 PM - 	Extension is not signed.
13-Apr-18 1:09:31 PM - 
13-Apr-18 1:09:31 PM - Searching for applicable products...
13-Apr-18 1:09:31 PM - Found installed product - Global Location
13-Apr-18 1:09:31 PM - Found installed product - Visual Studio Community 2017
13-Apr-18 1:09:31 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by zignd** [comment]
The extension is exclusively for Visual Studio Code.
