### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by kopach** [zignd/HTML-CSS-Class-Completion#254]
Hi. I'm facing quite often an issue with this extension. 

Here is log from console:

```
Extension Host
/Users/<user>/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4616
/Users/<user>/.vscode/extensions/zignd.html-css-class-completion-1.19.0/out/src/parse-engine-gateway.js:20
                resolve(data.toString());
                             ^TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.callback (/Users/<user>/.vscode/extensions/zignd.html-css-class-completion-1.19.0/out/src/parse-engine-gateway.js:20:30)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13)
```

Please, help to solve this

**Comment by kopach** [comment]
Faced same issue with other extension when this one was disabled. Therefore it must be an issue in something else
