### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by capaj** [zignd/HTML-CSS-Class-Completion#66]
```
/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Cannot read property 'length' of null: TypeError: Cannot read property 'length' of null
    at Object.provideCompletionItems (/home/capaj/.vscode/extensions/Zignd.html-css-class-completion-1.7.0/out/src/extension.js:77:27)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:356623
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:57373
    at new n.Class.derive._oncancel (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:46346)
    at Object.d [as asWinJsPromise] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:57336)
    at e.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:356577)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:365815
    at t._withAdapter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:360077)
    at t.$provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:365777)
    at t.e.handle (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:312304)
    at s (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:176531)
    at h (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:23:177208)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
e.onUnexpectedError @ /usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
```

This happened in version 1.7.0 of the extension.

**Comment by nealoke** [comment]
I also have this in my console. To give a bit more background this happens when typing in a regular `.js` file when not in a `className` tag (react) for me. Seems like it is trying to add autocompletes when not in the correct scope (`className`)

Is this something you could look into @zignd ?

![bug css](https://user-images.githubusercontent.com/17417414/29450948-08448542-8401-11e7-812a-8639cd93fc65.gif)

**Comment by zignd** [comment]
Yup, just fixed it. I'll be releasing a new version in a moment and thanks for reporting the bug.
